#!/bin/bash

#PBS -q normal
#PBS -l ncpus=1
#PBS -l walltime=00:20:00
#PBS -l mem=16GB
#PBS -l wd
#PBS -l storage=scratch/xh27+scratch/er01
#PBS -P md01
#PBS -N 5_diann
#PBS -o ./Logs/5_summarise.o
#PBS -e ./Logs/5_summarise.e

module load singularity

# CHANGE VARIABLES
diannImg=biocontainers-diann-v1.8.1_cv1.img
fasta=mouse_proteome.fasta
empirical_lib=mouse_proteome.empirical.speclib
mzMLDir=Expanded_mzML_complete

temp=./quant

#Add "--f" to the start of each mzML path
mzMLArray=()
for mzML in `ls -d ${mzMLDir}/*mzML`; do
	mzMLArray[${#mzMLArray[@]}]=$(echo '--f' ${mzML})
done

echo "Number of mzML files: ${#mzMLArray[@]}"

singularity exec ${diannImg} diann \
        ${mzMLArray[@]} \
        --fasta ${fasta} \
        --lib ${empirical_lib} \
        --threads ${PBS_NCPUS} \
        --verbose 4 \
        --individual-windows \
        --quick-mass-acc \
        --individual-mass-acc \
        --temp ${temp} \
        --relaxed-prot-inf \
        --pg-level 2 \
        --use-quant \
        --matrices \
        --out diann_report.tsv
