#!/bin/bash

# Project, storage and logs will be auto-updated at setup
# All variables will be auto-updated at setup
# There is no need to edit this script apart from 
# resources: CPU, MEM, JOBFS and TIME

#---------------------------- 

#---------------------------- 

#PBS -P xh27
#PBS -N step5
#PBS -l ncpus=<NCPUS>
#PBS -l mem=<MEM>GB
#PBS -l walltime=02:00:00
#PBS -l jobfs=10GB
#PBS -q normal
#PBS -W umask=022
#PBS -l wd
#PBS -o ./PBS_logs/step5_PXD050996_71s.o
#PBS -e ./PBS_logs/step5_PXD050996_71s.e
#PBS -l storage=scratch/er01+gdata/er01

module load singularity

set -e

#---------------------------- 

#---------------------------- 
# I/O (hard-coded, please do not change) 

libdir=3_empirical_library
temp=4_quant 
outdir=5_summarise

mkdir -p ${outdir}


#---------------------------- 

#---------------------------- 
# Inputs auto-updated when the setup script is run:

wine_tar=/scratch/er01/PIPE-3050-DIA-NN/thermo_raw/diann_resources/dot_wine_DIANN_SCIEX_THERMO.tar
wine_image=/scratch/er01/PIPE-3050-DIA-NN/thermo_raw/diann_resources/wine_7.0.0.sif
fasta_var_string="--fasta /scratch/er01/PIPE-3050-DIA-NN/thermo_raw/human_proteome/UP000005640_9606.fasta --fasta /scratch/er01/PIPE-3050-DIA-NN/thermo_raw/human_proteome/UP000005640_9606_additional.fasta "
empirical_lib=PXD050996_71s.empirical
final_out=PXD050996_71s_diann_report.tsv

#---------------------------- 

#---------------------------- 
# Establish scan window, mass accuracy and MS1 mass accuracy parameters:

scan_window=<value>
mass_acc=<value>
ms1_acc=<value>

if [[ $scan_window  =~ ^[0-9]+$ ]]
then  
        windows="--window ${scan_window}"
elif [[ $scan_window  =~ ^auto$ ]]
then
        windows="--individual-windows"
fi

if [[ $mass_acc  =~ ^[0-9.]+$ ]]
then  
        massacc="--mass-acc ${mass_acc}"
elif [[ $mass_acc  =~ ^auto$ ]]
then
        massacc="--individual-mass-acc --quick-mass-acc"
fi

massacc_and_windows="${windows} ${massacc}"

if [[ $ms1_acc =~ [1-9] ]] # Setup script ensures ms1_acc can only match numbers so can use this relaxed pattern here safely to easily bypass zero while allowing for non-integers
then
        massacc_and_windows+=" --mass-acc-ms1 ${ms1_acc}"
fi


#----------------------------

#----------------------------  
# Set up wine folder on jobfs:

tar xf ${wine_tar} -C ${PBS_JOBFS} 
WINEPREFIX=${PBS_JOBFS}/dot_wine
diann_exe=${WINEPREFIX}/drive_c/DIA-NN/1.8.1/DiaNN.exe


#----------------------------

#---------------------------- 
# Run DiaNN.exe with Wine singularity container:

extra_flags=""

singularity exec \
        --env WINEPREFIX=${WINEPREFIX} \
        --env WINEDEBUG=-all \
        ${wine_image} \
        wine \
        ${diann_exe} \
	--dir Raw_data \
	--lib ${libdir}/${empirical_lib} \
	${fasta_var_string} \
        --threads ${PBS_NCPUS} \
        --verbose 4 \
	--temp ${temp} \
        --pg-level 2 \
        --use-quant \
        --matrices \
	--qvalue 0.01 \
	--out ${outdir}/${final_out} \
	${massacc_and_windows} \
	${extra_flags} > ./Logs/5_summarise.log 2>&1
	

#-----------------------------------------
